// -*- C++ -*- generated by wxGlade 0.6.3

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FRAMEMAIN_H
#define FRAMEMAIN_H

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "bitmapFromMem.h"
#ifndef ICON_XPM
#define ICON_XPM
#include "res/klangwunder3000.xpm"
#include "evtids.h"
#endif
#include "res/playklang.png.h"
#include "res/stopklang.png.h"
#include "res/info.png.h"
#include "res/remove.png.h"
#include "res/add.png.h"
#include "res/stop.png.h"
#include "res/play.png.h"
#include "res/pause.png.h"

// end wxGlade


class FrameMain: public wxFrame {
public:
    // begin wxGlade: FrameMain::ids
    // end wxGlade

    FrameMain(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: FrameMain::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: FrameMain::attributes
    wxStaticBox* sizer_klangset_staticbox;
    wxMenuBar* frame_main_menubar;
    wxStatusBar* frame_main_statusbar;
    wxBitmapButton* button_playpause;
    wxBitmapButton* button_stop;
    wxStaticText* label_vol;
    wxSlider* slider_vol;
    wxBitmapButton* button_add;
    wxBitmapButton* button_remove;
    wxBitmapButton* button_info;
    wxBitmapButton* button_playklang;
    wxGrid* grid_klangs;
    wxPanel* panel_grid;
    wxPanel* panel_top;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void klangset_new(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_open(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_save(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_saveas(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_close(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void app_exit(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klang_add(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klang_remove(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klang_info(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klang_play(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void help_contents(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void help_about(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_playpause(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void klangset_stop(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void vol_change(wxScrollEvent &event); // wxGlade: <event_handler>
    virtual void grid_cell_change(wxGridEvent &event); // wxGlade: <event_handler>
    virtual void grid_cell_select(wxGridEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // FRAMEMAIN_H
